/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        default: {
          ...require("daisyui/src/colors/themes")["[data-theme=light]"],
          primary: "#FF00F4",
          secondary: "#FF7400",
          accent: "#CBFD03",
          neutral: "#191A3F",
          "base-100": "#f5f5f5",
          "base-200": "#fff",
          info: "#3194F6",
          success: "#5FC992",
          warning: "#F7DE2D",
          error: "#E60300",
          "--rounded-box": "1.25rem",
          "--rounded-btn": "1rem",
          "--rounded-badge": "1rem",
        },
      },
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
    ],
  },
};
